title: "QNet Wiki"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
# Define search options
search_enabled: true
# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 2
# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html